# Generated by Django 4.0.5 on 2022-09-02 18:46

import birduser.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField(null=True, verbose_name='Mobile Number')),
                ('area', models.CharField(blank=True, choices=[(None, 'Unknown'), ('North Region', 'North'), ('East Region', 'East'), ('North-East Region', 'Ne'), ('Central Region', 'Central'), ('West Region', 'West')], default='Unknown', max_length=20)),
                ('postalCode', models.IntegerField(null=True, verbose_name='Postal Code')),
                ('address1', models.CharField(max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='anonymousProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='birduser.address')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='anonymousRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuceDescription', models.TextField(blank=True, null=True, verbose_name='More information...')),
                ('requestTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('rescueRequester', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anoUser_request', to='birduser.anonymousprofile')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('species', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('adoptDescription', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('applyer', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=25, null=True)),
                ('avatar', models.ImageField(blank=True, default='userAvatar/default-user-icon-8.jpg', null=True, upload_to=birduser.models.user_icon_path)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_user', to='birduser.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userDonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transitionTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='rescueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuceDescription', models.TextField(blank=True, null=True, verbose_name='More information...')),
                ('requestTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('progress', models.TextField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('in_Progress', 'In Progress'), ('solved', 'Solved')], default='submitted')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='birduser.address')),
                ('rescueRequester', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_rescueRequest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='rescueBirdPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pict', models.ImageField(blank=True, default='', null=True, upload_to=birduser.models.user_rescue_request_picture)),
                ('anonymousRequest', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescueRequest', to='birduser.anonymousrequest')),
                ('rescue_pk', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_pictures', to='birduser.rescuerequest')),
            ],
        ),
        migrations.CreateModel(
            name='petAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.TextField(choices=[('Submitted', 'Submitted'), ('Accepted', 'Accepted'), ('looking for an adopter', 'Looking For Adopter'), ('transfering', 'Transfer Procedures'), ('solved', 'Solved')], default='Submitted')),
                ('time', models.TimeField(default=django.utils.timezone.now, null=True)),
                ('adopter', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='User_petAdption', to=settings.AUTH_USER_MODEL)),
                ('birds', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='birds_petAdoption', to='birduser.bird')),
                ('requester', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='birdPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pict', models.ImageField(blank=True, default='', null=True, upload_to=birduser.models.pet_adopt_request_picture)),
                ('bird', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='birduser.bird')),
            ],
        ),
    ]
