# Generated by Django 4.0.5 on 2022-09-02 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('birduser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petadoption',
            name='adopter',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='User_petAdption', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petadoption',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
